"""
About Research Team
"""

import streamlit as st

from utils.asset_loader import (
    INSTITUTION_LOGO,
)

st.set_page_config(
    page_title="About Research Team",
    page_icon="👨‍💻",
    layout="wide"
)


st.title("👨‍💻 About Research Team")

st.caption(
    "Research team profile and project information."
)

st.divider()

# ======================================================
# RESEARCH TEAM
# ======================================================

st.subheader("Research Team Profile")

col1, col2 = st.columns([1, 2])

with col1:

    st.image(
        INSTITUTION_LOGO,
        caption="Fakultas Teknologi Informasi — Universitas Sebelas April",
        use_column_width=True
    )

    st.markdown(
        """
### SIDIAS

**Research Team**
"""
    )

with col2:

    st.write(
        """

**Institution**

Universitas Sebelas April — Fakultas Teknologi Informasi
"""
    )

    st.markdown("### Research Members")

    st.write(
        """
- Virzan Pasa Nugraha
- Agung Febrian
- Fidi Supriadi
"""
    )


st.divider()

# ======================================================
# PROJECT INFORMATION
# ======================================================

st.subheader("Project Information")

col1, col2, col3 = st.columns(3)

with col1:

    st.metric(
        "Project",
        "SIDIAS"
    )

with col2:

    st.metric(
        "Machine Learning",
        "CatBoost"
    )

with col3:

    st.metric(
        "Framework",
        "Streamlit"
    )


st.divider()

# ======================================================
# APPLICATION FEATURES
# ======================================================

st.subheader("Application Features")

features = [

    "Early Diabetes Risk Prediction",

    "CatBoost Classification Model",

    "Probability-Based Risk Assessment",

    "Explainable Artificial Intelligence (SHAP)",

    "Algorithmic Fairness Evaluation",

    "Probability Calibration Analysis",

    "Threshold Optimization",

    "Interactive Research Dashboard"

]

for item in features:

    st.success(item)


st.divider()

# ======================================================
# SYSTEM ARCHITECTURE
# ======================================================

st.subheader("System Architecture")

st.code(
"""
User

   │

Streamlit Web Interface

   │

Data Validation & Preprocessing

   │

CatBoost Prediction Engine

   │

Probability Estimation

   │

Risk Classification

   │

Recommendation Generation

   │

Prediction Report
""",
language="text"
)


st.divider()

# ======================================================
# RESEARCH BASIS
# ======================================================

st.subheader("Research Basis")

st.info(
"""
SIDIAS is an interactive research prototype developed from
the published scientific study entitled:

'Comprehensive Diabetes Risk Prediction Using BRFSS Data:
Performance, Explainability, Fairness, and Calibration.'

The prototype transforms the published research methodology
into an interactive decision support application by
integrating machine learning prediction, explainable
artificial intelligence (SHAP), fairness evaluation,
probability calibration, and threshold optimization.

Detailed information regarding the research methodology,
scientific workflow, and research contributions is available
on the Research Foundation page.
"""
)


st.divider()

# ======================================================
# DISCLAIMER
# ======================================================

st.subheader("Disclaimer")

st.warning(
"""
SIDIAS is intended solely for research, educational,
and technology demonstration purposes.

The prediction results generated by this prototype should
not be interpreted as a medical diagnosis and must not
replace professional medical advice, diagnosis, or treatment.
Users should always consult qualified healthcare
professionals regarding their health conditions.
"""
)


st.divider()

# ======================================================
# RESEARCH INFORMATION
# ======================================================

st.subheader("Research Information")

st.info(
"""
SIDIAS is a research prototype designed to demonstrate the
practical implementation of trustworthy machine learning for
early diabetes risk prediction.

The application serves as a bridge between published
scientific research and an interactive decision support
system, enabling users to explore predictive performance,
model explainability, fairness, calibration, and threshold
optimization in a unified platform.
"""
)


st.caption(
    "© 2026 SIDIAS Research Team • Universitas Sebelas April • Version 1.0.0"
)